name: attendance_portal
description: تطبيق متابعة الحضور والانصراف للموظفين — شبكة الوزارة الداخلية
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  device_info_plus: ^13.2.0
  uuid: ^4.6.0
  intl: ^0.20.0
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
