name: attendance_portal
description: تطبيق متابعة الحضور والانصراف للموظفين — شبكة الوزارة الداخلية
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  device_info_plus: ^13.2.0
  uuid: ^4.4.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
